"""Add Gmail and Calendar integration tokens

Revision ID: 01acda49f390
Revises: d19a2734693b
Create Date: 2025-10-16 22:06:15.079822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01acda49f390'
down_revision: Union[str, Sequence[str], None] = 'd19a2734693b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('google_calendar_token', sa.String(), nullable=True))
    op.add_column('users', sa.Column('google_calendar_refresh', sa.String(), nullable=True))
    op.add_column('users', sa.Column('google_gmail_token', sa.String(), nullable=True))
    op.add_column('users', sa.Column('google_gmail_refresh', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'google_gmail_refresh')
    op.drop_column('users', 'google_gmail_token')
    op.drop_column('users', 'google_calendar_refresh')
    op.drop_column('users', 'google_calendar_token')
    # ### end Alembic commands ###
