"""add_tally_integration_fields

Revision ID: 9be769ec4648
Revises: 72e72a8e7b4b
Create Date: 2025-10-24 02:34:07.523022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9be769ec4648'
down_revision: Union[str, Sequence[str], None] = '72e72a8e7b4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('tally_server_url', sa.String(), nullable=True))
    op.add_column('users', sa.Column('tally_connected', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('tally_company_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'tally_company_name')
    op.drop_column('users', 'tally_connected')
    op.drop_column('users', 'tally_server_url')
    # ### end Alembic commands ###
