"""migrate_tally_to_sql

Revision ID: e16f4b328361
Revises: 285600fb5c84
Create Date: 2025-10-25 20:12:27.108211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e16f4b328361'
down_revision: Union[str, Sequence[str], None] = '285600fb5c84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('tally_database_name', sa.String(), nullable=True))
    op.drop_column('users', 'tally_server_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('tally_server_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('users', 'tally_database_name')
    # ### end Alembic commands ###
